apiVersion: v2
name: freqtrade
description: A Helm chart for Freqtrade
maintainers:
- name: Amirbekyan
  email: mousheghamirbekyan@gmail.com
type: application
version: 0.1.20
appVersion: stable
sources:
  - https://github.com/freqtrade/freqtrade
  - https://github.com/freqtrade/freqtrade/blob/develop/config_examples/config_full.example.json
  - https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies
  - https://freqst.com/
  - https://github.com/davidzr/freqtrade-strategies/
  - https://github.com/thraizz/freqtrade-dashboard/tree/main/collector
